### ISSUE TITLE
README and Python

### ISSUE THREAD

**Issue by shahinrostami** [BU-Computing/radar#1]
Hello @davidbain 

Fantastic work. Does this indeed work with any version of Python, or does it make a difference if you're using Python 2 or Python 3? If it does require a specific version it would be great to have it listed in the README so people can make sure to install it.

**Comment by jimmyjamesbaldwin** [comment]
Hey Shahin, the app was written using version 2.7 but I've had a look at the code and it will work with Python 3 if the dependency script (_app/deploy/install.sh_) is updated to use pip3 and the print statements are updated in _manage.py_ to use braces. If I get time I'll update the code so it works with both, will update the readme in the meantime.

Jimmy
